### ISSUE TITLE
Need to transition my company to new owner

### ISSUE THREAD

**Issue by blakeblackshear** [nashdev/jobs#185]
@egdelwonk The owner of our company on Nashdev Jobs is no longer with the company. What is the process to transition our company/listings to my email?

**Comment by egdelwonk** [comment]
Shoot me the company name (and id on nashdev if you have it) and i'll update.

**Comment by blakeblackshear** [comment]
Concert Genetics (https://jobs.nashdev.com/company/32)
My email on nashdev is `bblackshear@concertgenetics.com`

**Comment by egdelwonk** [comment]
Should be updated now.

**Comment by blakeblackshear** [comment]
Thanks!
